name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
        matrix:
          include:
            - repo: 'https://git.torproject.org/pluggable-transports/meek.git'
              directory: 'meek\meek-client'
              artifact-target: 'meek.exe'
              release-target: 'v0.37.0'

            - repo: 'https://git.torproject.org/pluggable-transports/obfs4.git'
              directory: 'obfs4\obfs4proxy'
              artifact-target: 'obfs4.exe'
              release-target: 'obfs4proxy-0.0.11'
              
            - repo: 'https://git.torproject.org/pluggable-transports/snowflake.git'
              directory: 'snowflake\proxy'
              artifact-target: 'snowflake.exe'
              release-target: 'v2.1.0'
              
    env:
      GOARCH: 386
      GOOS: windows

    steps:        
      - name: Clone Target Repo
        shell: cmd
        run: git clone ${{ matrix.repo }} --depth 1 --branch ${{ matrix.release-target }}

      - name: Build
        run: | 
          cd ${{ github.workspace }}\${{ matrix.directory }}
          go build -o ${{ github.workspace }}\${{ matrix.artifact-target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-target }}
          path: ${{ github.workspace }}\${{ matrix.artifact-target }}
          retention-days: 2
