name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
        matrix:
          include:
            - repo: 'https://git.torproject.org/pluggable-transports/meek.git'
              directory: 'meek\meek-client'
              artifact-target: 'meek.exe'

            - repo: 'https://git.torproject.org/pluggable-transports/obfs4.git'
              directory: 'obfs4\obfs4proxy'
              artifact-target: 'obfs4.exe'   
              
    env:
      GOARCH: 386
      GOOS: windows

    steps:        
      - name: Clone Target Repo
        shell: cmd
        run: git clone ${{ matrix.repo }}

      - name: Build
        run: | 
          cd ${{ github.workspace }}\${{ matrix.directory }}
          go build -o ${{ github.workspace }}\${{ matrix.artifact-target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-target }}
          path: ${{ github.workspace }}\${{ matrix.artifact-target }}
          retention-days: 2
