name: Build
on: push

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
        matrix:
          include:
            - repo: 'https://git.torproject.org/pluggable-transports/meek.git'
              directory: 'meek-client'
              artifact-target: 'meek.exe'

            - repo: 'https://git.torproject.org/pluggable-transports/obfs4.git'
              directory: './'
              artifact-target: 'obfs4.exe'   
              
    env:
      GOARCH: 386
      GOOS: windows
      SOURCE_DIR: ${{ env.GITHUB_WORKSPACE }}\src

    steps:
      - name: Clone Target Repo
        run: git clone ${{ matrix.repo }} $env:SOURCE_DIR

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}\${{ matrix.directory }}
        run: go build -o ${{ matrix.artifact-target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-target }}
          path: ${{ env.GITHUB_WORKSPACE }}\${{ matrix.artifact-target }}
